main.floors.jiakezi_3=
{
    "floorId": "jiakezi_3",
    "title": "劇本殺真相",
    "name": "劇本殺真相",
    "canFlyTo": false,
    "canFlyFrom": false,
    "canUseQuickShop": false,
    "cannotViewMap": true,
    "defaultGround": "ground",
    "images": [
        {
            "name": "ms_bg_becky_mansion.png",
            "canvas": "bg",
            "x": 0,
            "y": 0
        }
    ],
    "ratio": 1,
    "map": [
        [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0
        ],
        [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0
        ],
        [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0
        ],
        [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0
        ],
        [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0
        ],
        [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0
        ],
        [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0
        ],
        [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0
        ],
        [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0
        ],
        [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0
        ],
        [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0
        ],
        [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0
        ],
        [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0
        ]
    ],
    "width": 17,
    "height": 13,
    "firstArrive": [],
    "parallelDo": "",
    "events": {},
    "changeFloor": {},
    "beforeBattle": {},
    "afterGetItem": {},
    "afterOpenDoor": {},
    "autoEvent": {},
    "cannotMove": {},
    "cannotMoveIn": {},
    "bgmap": [],
    "fgmap": [],
    "eachArrive": [
        {
            "type": "setText",
            "avg": true,
            "position": "down",
            "offset": 0,
            "align": "left",
            "bold": true,
            "background": "winskin.png",
            "title": [
                255,
                225,
                80,
                1
            ],
            "text": [
                255,
                255,
                255,
                1
            ],
            "titlefont": 22,
            "textfont": 16,
            "lineHeight": 22,
            "time": 10,
            "letterSpacing": 0,
            "animateTime": 120
        },
        "伴隨著金髮少女的介紹結束，大家開始在房間內開始尋找線索。",
        "隨著大家移動到隔壁房間會議室時，臥倒在地上的屍體被發現了。",
        "氣氛開始變得焦灼起來，每一個人都在爭辯，為了自己的所作所為開脫。",
        "唯獨那金髮少女……事不關己的樣子，坐在位置上把玩著剪刀，彷彿事情與她無關。",
        "伴隨著線索逐一公開，討論也變得更加激烈。",
        "在現場中，最有嫌疑的三人為，公主、侍衛和王子。",
        "\t[GM]「請各位輪流發言，來解釋自己所做的一切事情。」",
        "\t[公主]「我來到這是為了來暗殺王子的，因為不滿政治婚姻而帶了瓶毒藥打算偷偷下毒。」",
        "\t[侍衛]「我與王子同行的目的只是他的護衛，至於為甚麼匕首出現在兇殺現場，這一點我完全不知道。」",
        "\t[王子]「為了能夠把公主帶回國，我準備了繩索與暗器，但是都還沒用就有人死了！」",
        {
            "type": "showImage",
            "code": 10,
            "image": "keng_neutral_portrait.png",
            "expression": "normal",
            "loc": [
                "portraitSpeakerX",
                "portraitSpeakerY"
            ],
            "opacity": 1,
            "time": 0
        },
        "\t[耿平]（在線索沒有錯誤的情況下，犯人肯定是這三人之中的其中一人，至於旁邊那位……）",
        {
            "type": "hideImage",
            "code": 10,
            "time": 0
        },
        "耿平看向了金髮少女，只見對方正閒得發慌，甚至已經將一隻手支在桌上，撐著自己的半張臉在看他們討論。",
        "似乎是感知到耿平在看金髮少女，金髮少女先是稍微睜大了點眼睛，隨後向耿平露出笑容。",
        "伴隨著公主、侍衛和王子的辯解結束，大家看向了金髮少女，金髮少女則無辜地露出微笑說",
        {
            "type": "showImage",
            "code": 20,
            "image": "jiakezi_smile.png",
            "expression": "smile",
            "loc": [
                "portraitSpeakerX",
                "portraitSpeakerY"
            ],
            "opacity": 1,
            "time": 0
        },
        "\t[金髮少女]「我一直坐在這邊，除了拍照線索之外，甚至都沒上廁所，身上也沒穿外衣，凶器又不在懷裡，這場遊戲跟我有啥幾巴關係？」",
        {
            "type": "hideImage",
            "code": 20,
            "time": 0
        },
        "對於金髮少女的反駁，大家都不好說些甚麼。",
        "最後得出結論，應該是公主的毒藥再來的路上不小心撒了幾滴出來，剛好滴在死者要喝的飲料裡面，所以死者死了。",
        "大家開心的互相交換聯絡方式，並跟ＧＭ復盤整盤遊戲，唯獨那個一直在旁觀的金髮少女，一直在往這偷笑著。",
        "．．．．．．",
        "隨著活動結束，其實梗平也不清楚自己到底是來這裡做什麼的，呼理呼塗地就完成了一場遊戲。",
        "一直到最後離開時，金髮少女說會收拾殘局讓大家先回去休息就好。",
        "不過在離開關上門的時候，彷彿聽到了有人說了一句……",
        {
            "type": "showImage",
            "code": 20,
            "image": "jiakezi_smile.png",
            "expression": "smile",
            "loc": [
                "portraitSpeakerX",
                "portraitSpeakerY"
            ],
            "opacity": 1,
            "time": 0
        },
        "\t[金髮少女]「笨蛋。」",
        {
            "type": "hideImage",
            "code": 20,
            "time": 0
        },
        "TE：蓬萊人形",
        "事件結束",
        {
            "type": "function",
            "function": "function () { core.plugin.completeAkibaEvent('jiakezi_3'); }"
        },
        {
            "type": "function",
            "function": "function () { core.plugin.returnToAkiba(); }"
        }
    ]
}
