main.floors.juju_1=
{
    "floorId": "juju_1",
    "title": "惡魔迷路",
    "name": "惡魔迷路",
    "canFlyTo": false,
    "canFlyFrom": false,
    "canUseQuickShop": false,
    "cannotViewMap": true,
    "defaultGround": "ground",
    "images": [
        {
            "name": "scene_road.png",
            "canvas": "bg",
            "x": 0,
            "y": 0
        }
    ],
    "bgm": "warped_surreal.mp3",
    "ratio": 1,
    "map": [
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0]
    ],
    "width": 13,
    "height": 13,
    "firstArrive": [],
    "eachArrive": [
        {
            "type": "setText",
            "position": "down",
            "offset": 8,
            "align": "left",
            "bold": true,
            "background": "winskin.png",
            "title": [255,225,80,1],
            "text": [255,255,255,1],
            "titlefont": 22,
            "textfont": 20,
            "lineHeight": 30,
            "time": 10,
            "letterSpacing": 0,
            "animateTime": 120
        },
        {"type": "hideImage", "code": 10, "time": 0, "async": true},
        {"type": "hideImage", "code": 14, "time": 0, "async": true},
        {"type": "showImage", "code": 10, "image": "keng_surprised_portrait.png", "loc": [28,210], "opacity": 1, "time": 0},
        "\t[梗平]奇怪？怎麼跑到這來了？",
        "\t[梗平]難道又是修卡的陰毛嗎？",
        {"type": "hideImage", "code": 10, "time": 0, "async": true},
        {"type": "showImage", "code": 14, "image": "juju_surprised.png", "loc": [220,185], "opacity": 1, "time": 0},
        "\t[茱茱]怎麼可能？而且應該是陰謀才對",
        {"type": "showImage", "code": 14, "image": "juju_angry.png", "loc": [220,185], "opacity": 1, "time": 0},
        "\t[茱茱]還是說你想說沒人，講黃色笑話？",
        {"type": "hideImage", "code": 14, "time": 0, "async": true},
        {"type": "showImage", "code": 10, "image": "keng_surprised_portrait.png", "loc": [28,210], "opacity": 1, "time": 0},
        "\t[梗平]欸？",
        {"type": "hideImage", "code": 10, "time": 0, "async": true},
        {"type": "showImage", "code": 14, "image": "juju_surprised.png", "loc": [220,185], "opacity": 1, "time": 0},
        "\t[茱茱]欸？難不成，你看得到我？",
        {"type": "hideImage", "code": 14, "time": 0, "async": true},
        {"type": "showImage", "code": 10, "image": "keng_neutral_portrait.png", "loc": [28,210], "opacity": 1, "time": 0},
        "\t[梗平]呃……是，看得很清楚",
        {"type": "hideImage", "code": 10, "time": 0, "async": true},
        {"type": "showImage", "code": 14, "image": "juju_panic.png", "loc": [220,185], "opacity": 1, "time": 0},
        "\t[茱茱]我的撒旦啊！總算找到人了！（嚎啕大哭）",
        {"type": "hideImage", "code": 14, "time": 0, "async": true},
        {"type": "showImage", "code": 10, "image": "keng_surprised_portrait.png", "loc": [28,210], "opacity": 1, "time": 0},
        "\t[梗平]欸！！！",
        {"type": "hideImage", "code": 10, "time": 0, "async": true},
        "一段時間後。",
        {"type": "showImage", "code": 14, "image": "juju_sad.png", "loc": [220,185], "opacity": 1, "time": 0},
        "\t[茱茱]噢抱歉，失態了，小人名叫茱茱",
        {"type": "showImage", "code": 14, "image": "juju_smile.png", "loc": [220,185], "opacity": 1, "time": 0},
        "\t[茱茱]如你所見，是個惡魔",
        {"type": "hideImage", "code": 14, "time": 0, "async": true},
        {"type": "showImage", "code": 10, "image": "keng_surprised_portrait.png", "loc": [28,210], "opacity": 1, "time": 0},
        "\t[梗平]惡魔？",
        {"type": "hideImage", "code": 10, "time": 0, "async": true},
        {"type": "showImage", "code": 14, "image": "juju_sad.png", "loc": [220,185], "opacity": 1, "time": 0},
        "\t[茱茱]我是一個月前被召喚的，但不曉得儀式出了什麼問題",
        "\t[茱茱]找不到召喚我的人，而且我也沒辦法回地獄了",
        {"type": "hideImage", "code": 14, "time": 0, "async": true},
        {"type": "showImage", "code": 10, "image": "keng_neutral_portrait.png", "loc": [28,210], "opacity": 1, "time": 0},
        "\t[梗平]你有沒有想過……找專業人士？",
        {"type": "hideImage", "code": 10, "time": 0, "async": true},
        {"type": "showImage", "code": 14, "image": "juju_angry.png", "loc": [220,185], "opacity": 1, "time": 0},
        "\t[茱茱]我找了！可他們只想從物理層面消滅我！",
        {"type": "showImage", "code": 14, "image": "juju_panic.png", "loc": [220,185], "opacity": 1, "time": 0},
        "\t[茱茱]拜託了，梗平大爺，把惡魔趕回地獄也算功德一件！",
        {"type": "hideImage", "code": 14, "time": 0, "async": true},
        {"type": "showImage", "code": 10, "image": "keng_surprised_portrait.png", "loc": [28,210], "opacity": 1, "time": 0},
        "\t[梗平]為什麼你會知道我的名字？",
        {"type": "hideImage", "code": 10, "time": 0, "async": true},
        {"type": "showImage", "code": 14, "image": "juju_smile.png", "loc": [220,185], "opacity": 1, "time": 0},
        "\t[茱茱]是我的能力，我還有辦法讓你變雖小",
        "\t[茱茱]具體來講，就是抽卡只能保底，一番賞只能抽最爛的",
        {"type": "hideImage", "code": 14, "time": 0, "async": true},
        {"type": "showImage", "code": 10, "image": "keng_panic_portrait.png", "loc": [28,210], "opacity": 1, "time": 0},
        "\t[梗平]好好好！我幫就是了",
        {"type": "hideImage", "code": 10, "time": 0, "async": true},
        {
            "type": "function",
            "function": "function () {\n\tcore.plugin.completeAkibaEvent('juju_1');\n}"
        },
        {
            "type": "function",
            "function": "function () {\n\tcore.plugin.addAkibaEvent({\n\t\t\"id\": \"juju_2\",\n\t\t\"title\": \"古書追逐\",\n\t\t\"locations\": [\"used_bookstore\"],\n\t\t\"floorId\": \"juju_2\",\n\t\t\"once\": true\n\t});\n}"
        },
        {
            "type": "function",
            "function": "function () {\n\tcore.plugin.returnToAkiba();\n}"
        }
    ],
    "parallelDo": "",
    "events": {},
    "changeFloor": {},
    "beforeBattle": {},
    "afterBattle": {},
    "afterGetItem": {},
    "afterOpenDoor": {},
    "autoEvent": {},
    "cannotMove": {},
    "cannotMoveIn": {},
    "bgmap": [],
    "fgmap": []
}
