main.floors.juju_2=
{
    "floorId": "juju_2",
    "title": "古書追逐",
    "name": "古書追逐",
    "canFlyTo": false,
    "canFlyFrom": false,
    "canUseQuickShop": false,
    "cannotViewMap": true,
    "defaultGround": "ground",
    "images": [
        {
            "name": "scene_mapo_shop.png",
            "canvas": "bg",
            "x": 0,
            "y": 0
        }
    ],
    "bgm": "dark_alleys_tension.ogg",
    "ratio": 1,
    "map": [
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0]
    ],
    "width": 13,
    "height": 13,
    "firstArrive": [],
    "eachArrive": [
        {
            "type": "setText",
            "position": "down",
            "offset": 8,
            "align": "left",
            "bold": true,
            "background": "winskin.png",
            "title": [255,225,80,1],
            "text": [255,255,255,1],
            "titlefont": 22,
            "textfont": 20,
            "lineHeight": 30,
            "time": 10,
            "letterSpacing": 0,
            "animateTime": 120
        },
        {"type": "hideImage", "code": 10, "time": 0, "async": true},
        {"type": "hideImage", "code": 14, "time": 0, "async": true},
        {"type": "showImage", "code": 14, "image": "juju_smile.png", "loc": [220,185], "opacity": 1, "time": 0},
        "\t[茱茱]對吼！古書店常會有奇奇怪怪的書籍",
        "\t[茱茱]梗平，你真是個天才",
        {"type": "hideImage", "code": 14, "time": 0, "async": true},
        {"type": "showImage", "code": 10, "image": "keng_smile_portrait.png", "loc": [28,210], "opacity": 1, "time": 0},
        "\t[梗平]哈哈！沒什麼啦～",
        {"type": "hideImage", "code": 10, "time": 0, "async": true},
        {"type": "showImage", "code": 14, "image": "juju_surprised.png", "loc": [220,185], "opacity": 1, "time": 0},
        "\t[茱茱]噢！找到了！＜如何把惡魔趕回地獄＞",
        {"type": "hideImage", "code": 14, "time": 0, "async": true},
        {"type": "showImage", "code": 10, "image": "keng_surprised_portrait.png", "loc": [28,210], "opacity": 1, "time": 0},
        "\t[梗平]怎麼這麼完美符合我們的需求",
        {"type": "showImage", "code": 10, "image": "keng_serious_portrait.png", "loc": [28,210], "opacity": 1, "time": 0},
        "\t[梗平]活像給我們挖坑跳一樣",
        {"type": "hideImage", "code": 10, "time": 0, "async": true},
        {"type": "showImage", "code": 14, "image": "juju_smile.png", "loc": [220,185], "opacity": 1, "time": 0},
        "\t[茱茱]總之我們打開看看吧！",
        {"type": "hideImage", "code": 14, "time": 0, "async": true},
        {"type": "showImage", "code": 10, "image": "keng_neutral_portrait.png", "loc": [28,210], "opacity": 1, "time": 0},
        "\t[梗平]噢…",
        {"type": "hideImage", "code": 10, "time": 0, "async": true},
        "\t[店主]喂！小伙子！不準白看書！",
        {"type": "showImage", "code": 10, "image": "keng_panic_portrait.png", "loc": [28,210], "opacity": 1, "time": 0},
        "\t[梗平]不好意思！我立刻買下來！",
        {"type": "hideImage", "code": 10, "time": 0, "async": true},
        "\t[店主]嗯？",
        "店主看了一下梗平。",
        "\t[店主]不用錢也行，你稍微讓我看一下",
        {"type": "showImage", "code": 14, "image": "juju_panic.png", "loc": [220,185], "opacity": 1, "time": 0},
        "\t[茱茱]梗平！拿了書快跑！他是退役驅魔師！",
        {"type": "hideImage", "code": 14, "time": 0, "async": true},
        {"type": "showImage", "code": 10, "image": "keng_surprised_portrait.png", "loc": [28,210], "opacity": 1, "time": 0},
        "\t[梗平]蛤？",
        {"type": "hideImage", "code": 10, "time": 0, "async": true},
        {"type": "showImage", "code": 14, "image": "juju_panic.png", "loc": [220,185], "opacity": 1, "time": 0},
        "\t[茱茱]跑！",
        {"type": "hideImage", "code": 14, "time": 0, "async": true},
        {"type": "showImage", "code": 10, "image": "keng_panic_portrait.png", "loc": [28,210], "opacity": 1, "time": 0},
        "\t[梗平]噢！",
        {"type": "hideImage", "code": 10, "time": 0, "async": true},
        "梗平撞倒了店主跑走。",
        "\t[店主]唉唷！真疼！剛才看到白白的一塊，果然是惡魔！",
        "\t[店主]等等！果然是什麼來着？而且我為啥這麼疼？",
        {
            "type": "function",
            "function": "function () {\n\tcore.plugin.completeAkibaEvent('juju_2');\n}"
        },
        {
            "type": "function",
            "function": "function () {\n\tcore.plugin.addAkibaEvent({\n\t\t\"id\": \"juju_3\",\n\t\t\"title\": \"回家法陣\",\n\t\t\"locations\": [\"tent\"],\n\t\t\"floorId\": \"juju_3\",\n\t\t\"once\": true\n\t});\n}"
        },
        {
            "type": "function",
            "function": "function () {\n\tcore.plugin.returnToAkiba();\n}"
        }
    ],
    "parallelDo": "",
    "events": {},
    "changeFloor": {},
    "beforeBattle": {},
    "afterBattle": {},
    "afterGetItem": {},
    "afterOpenDoor": {},
    "autoEvent": {},
    "cannotMove": {},
    "cannotMoveIn": {},
    "bgmap": [],
    "fgmap": []
}
