main.floors.juju_3=
{
    "floorId": "juju_3",
    "title": "回家法陣",
    "name": "回家法陣",
    "canFlyTo": false,
    "canFlyFrom": false,
    "canUseQuickShop": false,
    "cannotViewMap": true,
    "defaultGround": "ground",
    "images": [
        {
            "name": "scene_road.png",
            "canvas": "bg",
            "x": 0,
            "y": 0
        }
    ],
    "bgm": "next_to_you_emotional.mp3",
    "ratio": 1,
    "map": [
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0]
    ],
    "width": 13,
    "height": 13,
    "firstArrive": [],
    "eachArrive": [
        {
            "type": "setText",
            "position": "down",
            "offset": 8,
            "align": "left",
            "bold": true,
            "background": "winskin.png",
            "title": [255,225,80,1],
            "text": [255,255,255,1],
            "titlefont": 22,
            "textfont": 20,
            "lineHeight": 30,
            "time": 10,
            "letterSpacing": 0,
            "animateTime": 120
        },
        {"type": "hideImage", "code": 10, "time": 0, "async": true},
        {"type": "hideImage", "code": 14, "time": 0, "async": true},
        {"type": "showImage", "code": 10, "image": "keng_panic_portrait.png", "loc": [28,210], "opacity": 1, "time": 0},
        "\t[梗平]啊……累死我了",
        {"type": "hideImage", "code": 10, "time": 0, "async": true},
        {"type": "showImage", "code": 14, "image": "juju_smile.png", "loc": [220,185], "opacity": 1, "time": 0},
        "\t[茱茱]我對那個店長的記憶做了處理",
        "\t[茱茱]他一時半回也想不起我們",
        "\t[茱茱]好了，我看這書是真貨，趕緊操作吧！",
        {"type": "hideImage", "code": 14, "time": 0, "async": true},
        {"type": "showImage", "code": 10, "image": "keng_neutral_portrait.png", "loc": [28,210], "opacity": 1, "time": 0},
        "\t[梗平]噢好！",
        {"type": "hideImage", "code": 10, "time": 0, "async": true},
        "梗平按照書上步驟操作，完成法陣。",
        {"type": "showImage", "code": 10, "image": "keng_surprised_portrait.png", "loc": [28,210], "opacity": 1, "time": 0},
        "\t[梗平]最後一步，施術者須親吻惡魔……啥？",
        "\t[梗平]這書正經嗎！",
        {"type": "hideImage", "code": 10, "time": 0, "async": true},
        {"type": "showImage", "code": 14, "image": "juju_smile.png", "loc": [220,185], "opacity": 1, "time": 0},
        "\t[茱茱]這有什麼難的！",
        {"type": "hideImage", "code": 14, "time": 0, "async": true},
        "茱茱抱住梗平，對他來了個法式舌吻。",
        {"type": "showImage", "code": 10, "image": "keng_panic_portrait.png", "loc": [28,210], "opacity": 1, "time": 0},
        "\t[梗平]不是！那個！我想只要親手就好了",
        {"type": "hideImage", "code": 10, "time": 0, "async": true},
        {"type": "showImage", "code": 14, "image": "juju_surprised.png", "loc": [220,185], "opacity": 1, "time": 0},
        "\t[茱茱]噢……是說這是你的初吻？",
        {"type": "hideImage", "code": 14, "time": 0, "async": true},
        {"type": "showImage", "code": 10, "image": "keng_serious_portrait.png", "loc": [28,210], "opacity": 1, "time": 0},
        "\t[梗平]嗯",
        {"type": "hideImage", "code": 10, "time": 0, "async": true},
        "法陣開始發光。",
        {"type": "showImage", "code": 14, "image": "juju_smile.png", "loc": [220,185], "opacity": 1, "time": 0},
        "\t[茱茱]噢！可以回家啦！抱歉啦梗平！",
        "\t[茱茱]我會在地獄幫你留個VIP座位，就這樣，掰！",
        {"type": "hideImage", "code": 14, "time": 0, "async": true},
        {"type": "showImage", "code": 10, "image": "keng_surprised_portrait.png", "loc": [28,210], "opacity": 1, "time": 0},
        "\t[梗平]慢著！",
        {"type": "hideImage", "code": 10, "time": 0, "async": true},
        "茱茱消失了。",
        {"type": "showImage", "code": 10, "image": "keng_panic_portrait.png", "loc": [28,210], "opacity": 1, "time": 0},
        "\t[梗平]我也想上天堂好不好！",
        {"type": "hideImage", "code": 10, "time": 0, "async": true},
        "那一夜，梗平無法忘懷惡魔舌尖的觸感。",
        {
            "type": "function",
            "function": "function () {\n\tcore.plugin.completeAkibaEvent('juju_3');\n}"
        },
        {
            "type": "function",
            "function": "function () {\n\tcore.plugin.addAkibaEvent({\n\t\t\"id\": \"juju_4\",\n\t\t\"title\": \"裝死大成\",\n\t\t\"locations\": [\"park\"],\n\t\t\"floorId\": \"juju_4\",\n\t\t\"once\": true\n\t});\n}"
        },
        {
            "type": "function",
            "function": "function () {\n\tcore.plugin.returnToAkiba();\n}"
        }
    ],
    "parallelDo": "",
    "events": {},
    "changeFloor": {},
    "beforeBattle": {},
    "afterBattle": {},
    "afterGetItem": {},
    "afterOpenDoor": {},
    "autoEvent": {},
    "cannotMove": {},
    "cannotMoveIn": {},
    "bgmap": [],
    "fgmap": []
}
