main.floors.lei_3=
{
    "floorId": "lei_3",
    "title": "退魔課程",
    "name": "退魔課程",
    "canFlyTo": false,
    "canFlyFrom": false,
    "canUseQuickShop": false,
    "cannotViewMap": true,
    "defaultGround": "ground",
    "images": [
        {
            "name": "scene_street.png",
            "canvas": "bg",
            "x": 0,
            "y": 0
        }
    ],
    "bgm": "bgm.mp3",
    "ratio": 1,
    "map": [
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0]
    ],
    "width": 13,
    "height": 13,
    "firstArrive": [],
    "eachArrive": [
        {
            "type": "setText",
            "position": "down",
            "offset": 8,
            "align": "left",
            "bold": true,
            "background": "winskin.png",
            "title": [255,225,80,1],
            "text": [255,255,255,1],
            "titlefont": 22,
            "textfont": 20,
            "lineHeight": 30,
            "time": 10,
            "letterSpacing": 0,
            "animateTime": 120
        },
        {"type": "hideImage", "code": 10, "time": 0, "async": true},
        {"type": "hideImage", "code": 13, "time": 0, "async": true},
        {"type": "showImage", "code": 13, "image": "lei_smile.png", "loc": [220,185], "opacity": 1, "time": 0},
        "\t[累]梗平你來啦？那我們就開始上課",
        {"type": "hideImage", "code": 13, "time": 0, "async": true},
        "就這樣，累和梗平上了一整天的退魔課。",
        {"type": "showImage", "code": 13, "image": "lei_surprised.png", "loc": [220,185], "opacity": 1, "time": 0},
        "\t[累]真讓人意外，原本上這些課需要整整一年，你是什麼絕世大天才嗎？",
        {"type": "showImage", "code": 13, "image": "lei_happy.png", "loc": [220,185], "opacity": 1, "time": 0},
        "\t[累]乾脆當我徒弟算了",
        {"type": "hideImage", "code": 13, "time": 0, "async": true},
        {"type": "showImage", "code": 10, "image": "keng_smile_portrait.png", "loc": [28,210], "opacity": 1, "time": 0},
        "\t[梗平]承蒙厚愛，我考慮考慮……",
        {"type": "hideImage", "code": 10, "time": 0, "async": true},
        {"type": "showImage", "code": 13, "image": "lei_happy.png", "loc": [220,185], "opacity": 1, "time": 0},
        "\t[累]願意考慮就好啦！是說你還是處男嗎？",
        {"type": "hideImage", "code": 13, "time": 0, "async": true},
        {"type": "showImage", "code": 10, "image": "keng_surprised_portrait.png", "loc": [28,210], "opacity": 1, "time": 0},
        "\t[梗平]欸？(臉紅)",
        {"type": "hideImage", "code": 10, "time": 0, "async": true},
        {"type": "showImage", "code": 13, "image": "lei_smile.png", "loc": [220,185], "opacity": 1, "time": 0},
        "\t[累]啊……看這個樣子，絕對是了",
        "\t[累]姑且給你個福利好了",
        {"type": "hideImage", "code": 13, "time": 0, "async": true},
        "累抓住梗平的手襲向自己的胸部。",
        {"type": "showImage", "code": 10, "image": "keng_panic_portrait.png", "loc": [28,210], "opacity": 1, "time": 0},
        "\t[梗平]欸！不是！欸！(處男特有的詞彙量)",
        {"type": "hideImage", "code": 10, "time": 0, "async": true},
        {"type": "showImage", "code": 13, "image": "lei_smile.png", "loc": [220,185], "opacity": 1, "time": 0},
        "\t[累]I cup的手感不錯吧？當我徒弟可以每天揉喔…開玩笑的，我只是不想讓你留下遺憾",
        "\t[累]明天會是一場硬仗，記得多喝水，知道嗎！",
        {"type": "hideImage", "code": 13, "time": 0, "async": true},
        {"type": "showImage", "code": 10, "image": "keng_panic_portrait.png", "loc": [28,210], "opacity": 1, "time": 0},
        "\t[梗平]我知道了……",
        {"type": "hideImage", "code": 10, "time": 0, "async": true},
        "那一夜，梗平對I cup的手感久久無法忘懷。",
        {
            "type": "function",
            "function": "function () {\n\tcore.plugin.completeAkibaEvent('lei_3');\n}"
        },
        {
            "type": "function",
            "function": "function () {\n\tcore.plugin.addAkibaEvent({\n\t\t\"id\": \"lei_4\",\n\t\t\"title\": \"倉庫決戰\",\n\t\t\"locations\": [\"warehouse_district\"],\n\t\t\"floorId\": \"lei_4\",\n\t\t\"once\": true\n\t});\n}"
        },
        {
            "type": "function",
            "function": "function () {\n\tcore.plugin.returnToAkiba();\n}"
        }
    ],
    "parallelDo": "",
    "events": {},
    "changeFloor": {},
    "beforeBattle": {},
    "afterBattle": {},
    "afterGetItem": {},
    "afterOpenDoor": {},
    "autoEvent": {},
    "cannotMove": {},
    "cannotMoveIn": {},
    "bgmap": [],
    "fgmap": []
}
