main.floors.lei_4=
{
    "floorId": "lei_4",
    "title": "倉庫決戰",
    "name": "倉庫決戰",
    "canFlyTo": false,
    "canFlyFrom": false,
    "canUseQuickShop": false,
    "cannotViewMap": true,
    "defaultGround": "ground",
    "images": [
        {
            "name": "scene_street.png",
            "canvas": "bg",
            "x": 0,
            "y": 0
        }
    ],
    "bgm": "bgm.mp3",
    "ratio": 1,
    "map": [
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0]
    ],
    "width": 13,
    "height": 13,
    "firstArrive": [],
    "eachArrive": [
        {
            "type": "setText",
            "position": "down",
            "offset": 8,
            "align": "left",
            "bold": true,
            "background": "winskin.png",
            "title": [255,225,80,1],
            "text": [255,255,255,1],
            "titlefont": 22,
            "textfont": 20,
            "lineHeight": 30,
            "time": 10,
            "letterSpacing": 0,
            "animateTime": 120
        },
        {"type": "hideImage", "code": 10, "time": 0, "async": true},
        {"type": "hideImage", "code": 13, "time": 0, "async": true},
        {"type": "showImage", "code": 13, "image": "lei_sad.png", "loc": [220,185], "opacity": 1, "time": 0},
        "\t[累]梗平……看樣子你好像沒什麼遺憾了啊？",
        {"type": "showImage", "code": 13, "image": "lei_angry.png", "loc": [220,185], "opacity": 1, "time": 0},
        "\t[累]接下來，我會打開倉庫大門，把跑出來的全部宰掉!",
        {"type": "hideImage", "code": 13, "time": 0, "async": true},
        {"type": "showImage", "code": 10, "image": "keng_serious_portrait.png", "loc": [28,210], "opacity": 1, "time": 0},
        "\t[梗平]嗯！了解！",
        {"type": "hideImage", "code": 10, "time": 0, "async": true},
        {"type": "showImage", "code": 13, "image": "lei_happy.png", "loc": [220,185], "opacity": 1, "time": 0},
        "\t[累]好！上吧！",
        {"type": "hideImage", "code": 13, "time": 0, "async": true},
        "就這樣，惡靈們被累和梗平三下五除二解決，但是……",
        {"type": "showImage", "code": 13, "image": "lei_panic.png", "loc": [220,185], "opacity": 1, "time": 0},
        "\t[累]不好！還有一個！",
        {"type": "hideImage", "code": 13, "time": 0, "async": true},
        "巨大的惡靈手臂抓住梗平，把他舉在半空中。",
        {"type": "showImage", "code": 10, "image": "keng_panic_portrait.png", "loc": [28,210], "opacity": 1, "time": 0},
        "\t[梗平]累姐！救命啊！",
        {"type": "hideImage", "code": 10, "time": 0, "async": true},
        {"type": "showImage", "code": 13, "image": "lei_panic.png", "loc": [220,185], "opacity": 1, "time": 0},
        "\t[累]梗平！你直接尿褲子！",
        {"type": "hideImage", "code": 13, "time": 0, "async": true},
        {"type": "showImage", "code": 10, "image": "keng_surprised_portrait.png", "loc": [28,210], "opacity": 1, "time": 0},
        "\t[梗平]蛤？",
        {"type": "hideImage", "code": 10, "time": 0, "async": true},
        {"type": "showImage", "code": 13, "image": "lei_angry.png", "loc": [220,185], "opacity": 1, "time": 0},
        "\t[累]你尿就是了！",
        {"type": "hideImage", "code": 13, "time": 0, "async": true},
        "溫熱的尿液從梗平的褲子滲出。",
        "\t[惡靈]是童子尿！你好狠啊！",
        "惡靈在叫喊中散去。",
        "一段時間後。",
        {"type": "showImage", "code": 13, "image": "lei_happy.png", "loc": [220,185], "opacity": 1, "time": 0},
        "\t[累]來！替換的褲子和內褲，好在我有先見之明，讓你多喝水，哈哈！",
        {"type": "hideImage", "code": 13, "time": 0, "async": true},
        {"type": "showImage", "code": 10, "image": "keng_panic_portrait.png", "loc": [28,210], "opacity": 1, "time": 0},
        "\t[梗平]真是太好了呢……哈哈（苦笑）",
        {"type": "hideImage", "code": 10, "time": 0, "async": true},
        {"type": "showImage", "code": 13, "image": "lei_smile.png", "loc": [220,185], "opacity": 1, "time": 0},
        "\t[累]好啦～別這種臉嘛~來！這個給你的",
        {"type": "hideImage", "code": 13, "time": 0, "async": true},
        {"type": "showImage", "code": 10, "image": "keng_surprised_portrait.png", "loc": [28,210], "opacity": 1, "time": 0},
        "\t[梗平]這是？",
        {"type": "hideImage", "code": 10, "time": 0, "async": true},
        {"type": "showImage", "code": 13, "image": "lei_smile.png", "loc": [220,185], "opacity": 1, "time": 0},
        "\t[累]我這次工作的訂金和我的聯絡電話，你明知道我想收你的，這筆錢就當賄賂，你好好考慮一下",
        "\t[累]好啦，你該回家了，你的家人都在等你吧？",
        {"type": "showImage", "code": 13, "image": "lei_happy.png", "loc": [220,185], "opacity": 1, "time": 0},
        "\t[累]我要在這收拾殘局，再見啦！",
        {"type": "hideImage", "code": 13, "time": 0, "async": true},
        "就這樣，梗平又多了一個未來出路，以及一個新志向：揉巨乳揉到爽。",
        {
            "type": "function",
            "function": "function () {\n\tcore.plugin.completeAkibaEvent('lei_4');\n}"
        },
        {
            "type": "function",
            "function": "function () {\n\tcore.plugin.returnToAkiba();\n}"
        }
    ],
    "parallelDo": "",
    "events": {},
    "changeFloor": {},
    "beforeBattle": {},
    "afterBattle": {},
    "afterGetItem": {},
    "afterOpenDoor": {},
    "autoEvent": {},
    "cannotMove": {},
    "cannotMoveIn": {},
    "bgmap": [],
    "fgmap": []
}
