main.floors.lei_2=
{
    "floorId": "lei_2",
    "title": "退魔邀約",
    "name": "退魔邀約",
    "canFlyTo": false,
    "canFlyFrom": false,
    "canUseQuickShop": false,
    "cannotViewMap": true,
    "defaultGround": "ground",
    "images": [
        {
            "name": "scene_street.png",
            "canvas": "bg",
            "x": 0,
            "y": 0
        }
    ],
    "bgm": "bgm.mp3",
    "ratio": 1,
    "map": [
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0]
    ],
    "width": 13,
    "height": 13,
    "firstArrive": [],
    "eachArrive": [
        {
            "type": "setText",
            "position": "down",
            "offset": 8,
            "align": "left",
            "bold": true,
            "background": "winskin.png",
            "title": [255,225,80,1],
            "text": [255,255,255,1],
            "titlefont": 22,
            "textfont": 20,
            "lineHeight": 30,
            "time": 10,
            "letterSpacing": 0,
            "animateTime": 120
        },
        {"type": "hideImage", "code": 10, "time": 0, "async": true},
        {"type": "hideImage", "code": 13, "time": 0, "async": true},
        {"type": "showImage", "code": 13, "image": "lei_smile.png", "loc": [220,185], "opacity": 1, "time": 0},
        "\t[累]來了嗎？我還沒自我介紹吧？",
        "\t[累]我叫累，是位退魔師，小哥，你已經被惡靈纏上啦！",
        {"type": "hideImage", "code": 13, "time": 0, "async": true},
        {"type": "showImage", "code": 10, "image": "keng_surprised_portrait.png", "loc": [28,210], "opacity": 1, "time": 0},
        "\t[梗平]欸？惡靈是指？",
        {"type": "hideImage", "code": 10, "time": 0, "async": true},
        {"type": "showImage", "code": 13, "image": "lei_sad.png", "loc": [220,185], "opacity": 1, "time": 0},
        "\t[累]大概是一個月前，有邪教在這搞獻祭儀式，全員自殺，在那之後，跑到這邊的人，不管有沒有平安出來，都發生了不幸的事",
        {"type": "hideImage", "code": 13, "time": 0, "async": true},
        {"type": "showImage", "code": 10, "image": "keng_panic_portrait.png", "loc": [28,210], "opacity": 1, "time": 0},
        "\t[梗平]（狂冒冷汗）",
        {"type": "hideImage", "code": 10, "time": 0, "async": true},
        {"type": "showImage", "code": 13, "image": "lei_sad.png", "loc": [220,185], "opacity": 1, "time": 0},
        "\t[累]我原來是想用緩慢但安全的驅魔辦法的，不過，我看現在這種狀況，得和他們正面對決了，小哥，你叫什麼名字？",
        {"type": "hideImage", "code": 13, "time": 0, "async": true},
        {"type": "showImage", "code": 10, "image": "keng_neutral_portrait.png", "loc": [28,210], "opacity": 1, "time": 0},
        "\t[梗平]梗平……",
        {"type": "hideImage", "code": 10, "time": 0, "async": true},
        {"type": "showImage", "code": 13, "image": "lei_happy.png", "loc": [220,185], "opacity": 1, "time": 0},
        "\t[累]好，梗平，你得陪我一起除魔，不然可能會有漏網之魚",
        {"type": "hideImage", "code": 13, "time": 0, "async": true},
        {"type": "showImage", "code": 10, "image": "keng_surprised_portrait.png", "loc": [28,210], "opacity": 1, "time": 0},
        "\t[梗平]欸？",
        {"type": "hideImage", "code": 10, "time": 0, "async": true},
        {"type": "showImage", "code": 13, "image": "lei_angry.png", "loc": [220,185], "opacity": 1, "time": 0},
        "\t[累]欸什麼？你自找的，明天給我過來上課！",
        {"type": "hideImage", "code": 13, "time": 0, "async": true},
        {"type": "showImage", "code": 10, "image": "keng_panic_portrait.png", "loc": [28,210], "opacity": 1, "time": 0},
        "\t[梗平]是……",
        {"type": "hideImage", "code": 10, "time": 0, "async": true},
        {
            "type": "function",
            "function": "function () {\n\tcore.plugin.completeAkibaEvent('lei_2');\n}"
        },
        {
            "type": "function",
            "function": "function () {\n\tcore.plugin.addAkibaEvent({\n\t\t\"id\": \"lei_3\",\n\t\t\"title\": \"退魔課程\",\n\t\t\"locations\": [\"warehouse_district\"],\n\t\t\"floorId\": \"lei_3\",\n\t\t\"once\": true\n\t});\n}"
        },
        {
            "type": "function",
            "function": "function () {\n\tcore.plugin.returnToAkiba();\n}"
        }
    ],
    "parallelDo": "",
    "events": {},
    "changeFloor": {},
    "beforeBattle": {},
    "afterBattle": {},
    "afterGetItem": {},
    "afterOpenDoor": {},
    "autoEvent": {},
    "cannotMove": {},
    "cannotMoveIn": {},
    "bgmap": [],
    "fgmap": []
}
