main.floors.yuedu_ai_4=
{
    "floorId": "yuedu_ai_4",
    "title": "希望之花",
    "name": "希望之花",
    "canFlyTo": false,
    "canFlyFrom": false,
    "canUseQuickShop": false,
    "cannotViewMap": true,
    "defaultGround": "ground",
    "images": [
        {
            "name": "scene_mapo_shop.png",
            "canvas": "bg",
            "x": 0,
            "y": 0
        }
    ],
    "bgm": "next_to_you_emotional.mp3",
    "ratio": 1,
    "map": [
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0]
    ],
    "width": 13,
    "height": 13,
    "firstArrive": [],
    "eachArrive": [
        {
            "type": "setText",
            "position": "down",
            "offset": 8,
            "align": "left",
            "bold": true,
            "background": "winskin.png",
            "title": [255,225,80,1],
            "text": [255,255,255,1],
            "titlefont": 22,
            "textfont": 20,
            "lineHeight": 30,
            "time": 10,
            "letterSpacing": 0,
            "animateTime": 120
        },
        {"type": "hideImage", "code": 1, "time": 0, "async": true},
        {"type": "hideImage", "code": 10, "time": 0, "async": true},
        {"type": "hideImage", "code": 13, "time": 0, "async": true},
        "梗平仿佛被什麼吸引又來到這裡……那是母性與酒的魅惑……",
        {"type": "showImage", "code": 13, "image": "yuedu_smile.png", "loc": [220,185], "opacity": 1, "time": 0},
        "\t[月讀愛]哦也？今天也來嗎？遇到什麼好事嗎？梗平小弟。",
        {"type": "hideImage", "code": 13, "time": 0, "async": true},
        {"type": "showImage", "code": 10, "image": "keng_neutral_portrait.png", "loc": [28,210], "opacity": 1, "time": 0},
        "\t[梗平]不，就是喝酒放鬆……還有……",
        {"type": "hideImage", "code": 10, "time": 0, "async": true},
        {"type": "showImage", "code": 13, "image": "yuedu_surprised.png", "loc": [220,185], "opacity": 1, "time": 0},
        "\t[月讀愛]還有什麼？",
        {"type": "hideImage", "code": 13, "time": 0, "async": true},
        {"type": "showImage", "code": 10, "image": "keng_smile_portrait.png", "loc": [28,210], "opacity": 1, "time": 0},
        "\t[梗平]想見一下小愛大姐頭而已",
        {"type": "hideImage", "code": 10, "time": 0, "async": true},
        {"type": "showImage", "code": 13, "image": "yuedu_happy.png", "loc": [220,185], "opacity": 1, "time": 0},
        "\t[月讀愛]啊？哇哈哈！梗平小弟你就是這樣露出軟弱一面去把妹的嗎？真好笑呢！先來喝酒吧！",
        {"type": "hideImage", "code": 13, "time": 0, "async": true},
        {"type": "showImage", "code": 10, "image": "keng_smile_portrait.png", "loc": [28,210], "opacity": 1, "time": 0},
        "\t[梗平]啊哈哈……是呢！來喝吧！小愛大姐頭！",
        {"type": "hideImage", "code": 10, "time": 0, "async": true},
        {"type": "showImage", "code": 13, "image": "yuedu_smile.png", "loc": [220,185], "opacity": 1, "time": 0},
        "\t[月讀愛]嗯哼嗯哼，對了，咱之前說過會告訴你咱的事吧？",
        {"type": "hideImage", "code": 13, "time": 0, "async": true},
        {"type": "showImage", "code": 10, "image": "keng_neutral_portrait.png", "loc": [28,210], "opacity": 1, "time": 0},
        "\t[梗平]啊，確實有這麼一回事。",
        {"type": "hideImage", "code": 10, "time": 0, "async": true},
        {"type": "showImage", "code": 13, "image": "yuedu_smile.png", "loc": [220,185], "opacity": 1, "time": 0},
        "\t[月讀愛]你覺得咱這裡是什麼地方？",
        {"type": "hideImage", "code": 13, "time": 0, "async": true},
        {"type": "showImage", "code": 10, "image": "keng_neutral_portrait.png", "loc": [28,210], "opacity": 1, "time": 0},
        "\t[梗平]酒吧？",
        {"type": "hideImage", "code": 10, "time": 0, "async": true},
        {"type": "showImage", "code": 13, "image": "yuedu_happy.png", "loc": [220,185], "opacity": 1, "time": 0},
        "\t[月讀愛]雜貨店啦～哇哈哈！咱身體離不開酒了……每天煩心的事一件接一件…只有在喝酒時才能忘掉一切…",
        {"type": "hideImage", "code": 13, "time": 0, "async": true},
        {"type": "showImage", "code": 10, "image": "keng_serious_portrait.png", "loc": [28,210], "opacity": 1, "time": 0},
        "\t[梗平]小愛大姐頭，你這是醉了嗎？",
        {"type": "hideImage", "code": 10, "time": 0, "async": true},
        {"type": "showImage", "code": 13, "image": "yuedu_sad.png", "loc": [220,185], "opacity": 1, "time": 0},
        "\t[月讀愛]沒有沒有，梗平老弟在小看咱嗎？就是說說咱的事情而已～",
        {"type": "hideImage", "code": 13, "time": 0, "async": true},
        {"type": "showImage", "code": 10, "image": "keng_neutral_portrait.png", "loc": [28,210], "opacity": 1, "time": 0},
        "\t[梗平]是這樣嗎？",
        {"type": "hideImage", "code": 10, "time": 0, "async": true},
        {"type": "showImage", "code": 13, "image": "yuedu_sad.png", "loc": [220,185], "opacity": 1, "time": 0},
        "\t[月讀愛]社會之壓、他人之怨、不公之害……一旦不喝酒就會想起那些東西令人煩惱不是嗎？",
        {"type": "hideImage", "code": 13, "time": 0, "async": true},
        {"type": "showImage", "code": 10, "image": "keng_serious_portrait.png", "loc": [28,210], "opacity": 1, "time": 0},
        "\t[梗平]啊……是這樣呢……",
        {"type": "hideImage", "code": 10, "time": 0, "async": true},
        {"type": "showImage", "code": 13, "image": "yuedu_happy.png", "loc": [220,185], "opacity": 1, "time": 0},
        "\t[月讀愛]嗯！像這樣喝個痛快就暢所欲言呢！梗平老弟也多喝多說！",
        {"type": "hideImage", "code": 13, "time": 0, "async": true},
        {"type": "showImage", "code": 10, "image": "keng_smile_portrait.png", "loc": [28,210], "opacity": 1, "time": 0},
        "\t[梗平]那可當然呢！",
        {"type": "hideImage", "code": 10, "time": 0, "async": true},
        {"type": "showImage", "code": 13, "image": "yuedu_smile.png", "loc": [220,185], "opacity": 1, "time": 0},
        "\t[月讀愛]有點詠唱文的意味呢～那就來玩玩吧！那個！",
        {"type": "hideImage", "code": 13, "time": 0, "async": true},
        {"type": "showImage", "code": 10, "image": "keng_surprised_portrait.png", "loc": [28,210], "opacity": 1, "time": 0},
        "\t[梗平]那個是指？",
        {"type": "hideImage", "code": 10, "time": 0, "async": true},
        {"type": "showImage", "code": 13, "image": "yuedu_smile.png", "loc": [220,185], "opacity": 1, "time": 0},
        "\t[月讀愛]哼哼～團長，車已經準備好了！",
        {"type": "hideImage", "code": 13, "time": 0, "async": true},
        {"type": "showImage", "code": 10, "image": "keng_smile_portrait.png", "loc": [28,210], "opacity": 1, "time": 0},
        "\t[梗平]哦哦！那麼我走了！",
        {"type": "hideImage", "code": 10, "time": 0, "async": true},
        "月讀愛左右踏步轉轉圈～",
        "梗平也追著其身後跑火車～",
        {"type": "showImage", "code": 1, "image": "scene_street.png", "loc": [0,0], "opacity": 1, "time": 300},
        "熟悉的街角。",
        {"type": "showImage", "code": 13, "image": "yuedu_smile.png", "loc": [220,185], "opacity": 1, "time": 0},
        "\t[月讀愛]感覺真安靜啊，街上也沒有號角的人，和總部差別真大啊。",
        {"type": "hideImage", "code": 13, "time": 0, "async": true},
        {"type": "showImage", "code": 10, "image": "keng_neutral_portrait.png", "loc": [28,210], "opacity": 1, "time": 0},
        "\t[梗平]啊，可能是他們把火星的戰力都調到那裡去了。",
        {"type": "hideImage", "code": 10, "time": 0, "async": true},
        {"type": "showImage", "code": 13, "image": "yuedu_smile.png", "loc": [220,185], "opacity": 1, "time": 0},
        "\t[月讀愛]不過這也和咱們沒有關係了。",
        {"type": "hideImage", "code": 13, "time": 0, "async": true},
        {"type": "showImage", "code": 10, "image": "keng_neutral_portrait.png", "loc": [28,210], "opacity": 1, "time": 0},
        "\t[梗平]你心情很愉快啊。",
        {"type": "hideImage", "code": 10, "time": 0, "async": true},
        {"type": "showImage", "code": 13, "image": "yuedu_happy.png", "loc": [220,185], "opacity": 1, "time": 0},
        "\t[月讀愛]那是當然的了！大家也有救了，塔卡基又那麼努力，我也是加把勁騎士！",
        {"type": "hideImage", "code": 13, "time": 0, "async": true},
        {"type": "showImage", "code": 10, "image": "keng_smile_portrait.png", "loc": [28,210], "opacity": 1, "time": 0},
        "\t[梗平]啊，沒錯，我們至今為止所做一切並不是徒勞的。今後也是，只要咱們不停下腳步，道路就會不斷延伸。",
        {"type": "hideImage", "code": 10, "time": 0, "async": true},
        {"type": "showImage", "code": 13, "image": "yuedu_happy.png", "loc": [220,185], "opacity": 1, "time": 0},
        "\t[月讀愛]太長了太長了～哇哈哈！快倒下快倒下～",
        {"type": "hideImage", "code": 13, "time": 0, "async": true},
        {"type": "showImage", "code": 10, "image": "keng_panic_portrait.png", "loc": [28,210], "opacity": 1, "time": 0},
        "\t[梗平]👆（團長模仿躺地）",
        {"type": "hideImage", "code": 10, "time": 0, "async": true},
        {"type": "showImage", "code": 13, "image": "yuedu_happy.png", "loc": [220,185], "opacity": 1, "time": 0},
        "\t[月讀愛]哇哈哈！超像的超像的！啊～遊戲中心好像有那人在呢！",
        {"type": "hideImage", "code": 13, "time": 0, "async": true},
        {"type": "showImage", "code": 10, "image": "keng_surprised_portrait.png", "loc": [28,210], "opacity": 1, "time": 0},
        "\t[梗平]是這樣嗎？",
        {"type": "hideImage", "code": 10, "time": 0, "async": true},
        {"type": "showImage", "code": 13, "image": "yuedu_smile.png", "loc": [220,185], "opacity": 1, "time": 0},
        "\t[月讀愛]秋葉原可是充滿可能性之街呢～梗平小弟！",
        {"type": "hideImage", "code": 13, "time": 0, "async": true},
        {"type": "showImage", "code": 10, "image": "keng_surprised_portrait.png", "loc": [28,210], "opacity": 1, "time": 0},
        "\t[梗平]什麼啊…那是……",
        {"type": "hideImage", "code": 10, "time": 0, "async": true},
        {"type": "showImage", "code": 13, "image": "yuedu_happy.png", "loc": [220,185], "opacity": 1, "time": 0},
        "\t[月讀愛]嗯哼哼，能用玩梗令你心情愉快就好呢～秋葉原可是愛與希望之街～還有酒！不能不喝！今天也喝個痛快吧！",
        {"type": "hideImage", "code": 13, "time": 0, "async": true},
        {"type": "showImage", "code": 10, "image": "keng_smile_portrait.png", "loc": [28,210], "opacity": 1, "time": 0},
        "\t[梗平]啊！那可是當然的！",
        {"type": "hideImage", "code": 10, "time": 0, "async": true},
        "梗平與月讀愛借著酒勁愉快地玩梗，感覺某個地方的希望之花又綻開了。",
        {"type": "hideImage", "code": 1, "time": 0, "async": true},
        {
            "type": "function",
            "function": "function () {\n\tcore.plugin.completeAkibaEvent('yuedu_ai_4');\n}"
        },
        {
            "type": "function",
            "function": "function () {\n\tcore.plugin.returnToAkiba();\n}"
        }
    ],
    "parallelDo": "",
    "events": {},
    "changeFloor": {},
    "beforeBattle": {},
    "afterBattle": {},
    "afterGetItem": {},
    "afterOpenDoor": {},
    "autoEvent": {},
    "cannotMove": {},
    "cannotMoveIn": {},
    "bgmap": [],
    "fgmap": []
}
