main.floors.yuedu_ai_3=
{
    "floorId": "yuedu_ai_3",
    "title": "大姐頭",
    "name": "大姐頭",
    "canFlyTo": false,
    "canFlyFrom": false,
    "canUseQuickShop": false,
    "cannotViewMap": true,
    "defaultGround": "ground",
    "images": [
        {
            "name": "scene_mapo_shop.png",
            "canvas": "bg",
            "x": 0,
            "y": 0
        }
    ],
    "bgm": "bgm.mp3",
    "ratio": 1,
    "map": [
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0]
    ],
    "width": 13,
    "height": 13,
    "firstArrive": [],
    "eachArrive": [
        {
            "type": "setText",
            "position": "down",
            "offset": 8,
            "align": "left",
            "bold": true,
            "background": "winskin.png",
            "title": [255,225,80,1],
            "text": [255,255,255,1],
            "titlefont": 22,
            "textfont": 20,
            "lineHeight": 30,
            "time": 10,
            "letterSpacing": 0,
            "animateTime": 120
        },
        {"type": "hideImage", "code": 10, "time": 0, "async": true},
        {"type": "hideImage", "code": 13, "time": 0, "async": true},
        {"type": "showImage", "code": 13, "image": "yuedu_smile.png", "loc": [220,185], "opacity": 1, "time": 0},
        "\t[月讀愛]哦也？這不是梗平小弟嗎！又遇到什麼好事嗎？",
        {"type": "hideImage", "code": 13, "time": 0, "async": true},
        {"type": "showImage", "code": 10, "image": "keng_surprised_portrait.png", "loc": [28,210], "opacity": 1, "time": 0},
        "\t[梗平]啊，不是，怎麼我變小弟了…小愛…",
        {"type": "hideImage", "code": 10, "time": 0, "async": true},
        {"type": "showImage", "code": 13, "image": "yuedu_happy.png", "loc": [220,185], "opacity": 1, "time": 0},
        "\t[月讀愛]哇哈哈！這種叫法不是顯得咱像大姐頭嗎？怎麼？不喜歡嗎？",
        {"type": "hideImage", "code": 13, "time": 0, "async": true},
        {"type": "showImage", "code": 10, "image": "keng_neutral_portrait.png", "loc": [28,210], "opacity": 1, "time": 0},
        "\t[梗平]嘛，也沒關係吧……今天只是覺得有點不順心就走到這裡了……",
        {"type": "hideImage", "code": 10, "time": 0, "async": true},
        {"type": "showImage", "code": 13, "image": "yuedu_happy.png", "loc": [220,185], "opacity": 1, "time": 0},
        "\t[月讀愛]就是把咱這地方當解壓場所嗎！真不錯呢不錯呢！那麼來開喝吧！",
        {"type": "hideImage", "code": 13, "time": 0, "async": true},
        {"type": "showImage", "code": 10, "image": "keng_serious_portrait.png", "loc": [28,210], "opacity": 1, "time": 0},
        "\t[梗平]不，整天喝酒對身體不好吧……嗯？為什麼小愛身上沒有酒臭的？",
        {"type": "hideImage", "code": 10, "time": 0, "async": true},
        {"type": "showImage", "code": 13, "image": "yuedu_smile.png", "loc": [220,185], "opacity": 1, "time": 0},
        "\t[月讀愛]哼哼哼，這可是商業機密呢！想知道更多關咱的事就來酒會吧！梗平。",
        {"type": "hideImage", "code": 13, "time": 0, "async": true},
        {"type": "showImage", "code": 10, "image": "keng_smile_portrait.png", "loc": [28,210], "opacity": 1, "time": 0},
        "\t[梗平]哦哦！誰怕誰啊！就喝個痛快吧！",
        {"type": "hideImage", "code": 10, "time": 0, "async": true},
        "………",
        "……",
        "…",
        {"type": "showImage", "code": 10, "image": "keng_panic_portrait.png", "loc": [28,210], "opacity": 1, "time": 0},
        "\t[梗平]修卡那些混…嗝……混帳們…想破壞comike…嗝…我不會讓那種事發生的…",
        {"type": "hideImage", "code": 10, "time": 0, "async": true},
        {"type": "showImage", "code": 13, "image": "yuedu_smile.png", "loc": [220,185], "opacity": 1, "time": 0},
        "\t[月讀愛]哇哈哈，酒量不太好呢！梗平～哦哦，修卡嗎？那是什麼？聽上去真有趣呢！",
        {"type": "hideImage", "code": 13, "time": 0, "async": true},
        {"type": "showImage", "code": 10, "image": "keng_panic_portrait.png", "loc": [28,210], "opacity": 1, "time": 0},
        "\t[梗平]那是……邪惡……嗝",
        {"type": "hideImage", "code": 10, "time": 0, "async": true},
        {"type": "showImage", "code": 13, "image": "yuedu_happy.png", "loc": [220,185], "opacity": 1, "time": 0},
        "\t[月讀愛]乖乖，看來梗平小弟就是對抗邪惡的正義伙伴呢！咱會給你應援喔！加油加油～",
        {"type": "hideImage", "code": 13, "time": 0, "async": true},
        {"type": "showImage", "code": 10, "image": "keng_panic_portrait.png", "loc": [28,210], "opacity": 1, "time": 0},
        "\t[梗平]嗝……",
        {"type": "hideImage", "code": 10, "time": 0, "async": true},
        "梗平在月讀愛的安慰下，壓力值下降了，把月讀愛視為大姐頭了。",
        {
            "type": "function",
            "function": "function () {\n\tcore.plugin.completeAkibaEvent('yuedu_ai_3');\n}"
        },
        {
            "type": "function",
            "function": "function () {\n\tcore.plugin.addAkibaEvent({\n\t\t\"id\": \"yuedu_ai_4\",\n\t\t\"title\": \"希望之花\",\n\t\t\"locations\": [\"convenience_24h\"],\n\t\t\"floorId\": \"yuedu_ai_4\",\n\t\t\"once\": true\n\t});\n}"
        },
        {
            "type": "function",
            "function": "function () {\n\tcore.plugin.returnToAkiba();\n}"
        }
    ],
    "parallelDo": "",
    "events": {},
    "changeFloor": {},
    "beforeBattle": {},
    "afterBattle": {},
    "afterGetItem": {},
    "afterOpenDoor": {},
    "autoEvent": {},
    "cannotMove": {},
    "cannotMoveIn": {},
    "bgmap": [],
    "fgmap": []
}
