main.floors.yuedu_ai_2=
{
    "floorId": "yuedu_ai_2",
    "title": "暢快酒會",
    "name": "暢快酒會",
    "canFlyTo": false,
    "canFlyFrom": false,
    "canUseQuickShop": false,
    "cannotViewMap": true,
    "defaultGround": "ground",
    "images": [
        {
            "name": "scene_mapo_shop.png",
            "canvas": "bg",
            "x": 0,
            "y": 0
        }
    ],
    "bgm": "bgm.mp3",
    "ratio": 1,
    "map": [
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0]
    ],
    "width": 13,
    "height": 13,
    "firstArrive": [],
    "eachArrive": [
        {
            "type": "setText",
            "position": "down",
            "offset": 8,
            "align": "left",
            "bold": true,
            "background": "winskin.png",
            "title": [255,225,80,1],
            "text": [255,255,255,1],
            "titlefont": 22,
            "textfont": 20,
            "lineHeight": 30,
            "time": 10,
            "letterSpacing": 0,
            "animateTime": 120
        },
        {"type": "hideImage", "code": 10, "time": 0, "async": true},
        {"type": "hideImage", "code": 13, "time": 0, "async": true},
        {"type": "showImage", "code": 10, "image": "keng_neutral_portrait.png", "loc": [28,210], "opacity": 1, "time": 0},
        "\t[梗平]……不知不覺又走到這裡了",
        {"type": "hideImage", "code": 10, "time": 0, "async": true},
        {"type": "showImage", "code": 13, "image": "yuedu_happy.png", "loc": [220,185], "opacity": 1, "time": 0},
        "\t[月讀愛]哦哦，梗平呢！終於想找個酒友嗎？怎樣，累了吧，先來喝一杯，呼呼～",
        {"type": "hideImage", "code": 13, "time": 0, "async": true},
        {"type": "showImage", "code": 10, "image": "keng_surprised_portrait.png", "loc": [28,210], "opacity": 1, "time": 0},
        "\t[梗平]這是……啤酒？",
        {"type": "hideImage", "code": 10, "time": 0, "async": true},
        {"type": "showImage", "code": 13, "image": "yuedu_angry.png", "loc": [220,185], "opacity": 1, "time": 0},
        "\t[月讀愛]啊？不合口味嗎？生命之水、威士忌那些更適合你嗎？",
        {"type": "hideImage", "code": 13, "time": 0, "async": true},
        {"type": "showImage", "code": 10, "image": "keng_smile_portrait.png", "loc": [28,210], "opacity": 1, "time": 0},
        "\t[梗平]不不，啤酒就行了，我不客氣了！",
        {"type": "hideImage", "code": 10, "time": 0, "async": true},
        {"type": "showImage", "code": 13, "image": "yuedu_smile.png", "loc": [220,185], "opacity": 1, "time": 0},
        "\t[月讀愛]嗯哼哼，哇哈哈！真不錯呢！叫咱做小愛吧～",
        {"type": "hideImage", "code": 13, "time": 0, "async": true},
        {"type": "showImage", "code": 10, "image": "keng_neutral_portrait.png", "loc": [28,210], "opacity": 1, "time": 0},
        "\t[梗平]哦哦……小愛",
        {"type": "hideImage", "code": 10, "time": 0, "async": true},
        {"type": "showImage", "code": 13, "image": "yuedu_happy.png", "loc": [220,185], "opacity": 1, "time": 0},
        "\t[月讀愛]哇哈哈，真不錯呢！有什麼想趁著酒會想說的嗎？",
        {"type": "hideImage", "code": 13, "time": 0, "async": true},
        {"type": "showImage", "code": 10, "image": "keng_serious_portrait.png", "loc": [28,210], "opacity": 1, "time": 0},
        "\t[梗平]其實呢……我在這發生了這些那些……",
        {"type": "hideImage", "code": 10, "time": 0, "async": true},
        {"type": "showImage", "code": 13, "image": "yuedu_smile.png", "loc": [220,185], "opacity": 1, "time": 0},
        "\t[月讀愛]哦…哦也？真是不容易呢！要大姐姐咱給你安慰安慰嗎？",
        {"type": "hideImage", "code": 13, "time": 0, "async": true},
        {"type": "showImage", "code": 10, "image": "keng_panic_portrait.png", "loc": [28,210], "opacity": 1, "time": 0},
        "\t[梗平]嗚哇哇！！大姐姐！",
        {"type": "hideImage", "code": 10, "time": 0, "async": true},
        {"type": "showImage", "code": 13, "image": "yuedu_happy.png", "loc": [220,185], "opacity": 1, "time": 0},
        "\t[月讀愛]哇哈哈！趁著酒勁一股腦盡情說個痛快吧！不醉無歸？哇哈哈！",
        {"type": "hideImage", "code": 13, "time": 0, "async": true},
        "梗平和月讀愛進行了一場暢快酒會的樣子，壓力值下降了。",
        {
            "type": "function",
            "function": "function () {\n\tcore.plugin.completeAkibaEvent('yuedu_ai_2');\n}"
        },
        {
            "type": "function",
            "function": "function () {\n\tcore.plugin.addAkibaEvent({\n\t\t\"id\": \"yuedu_ai_3\",\n\t\t\"title\": \"大姐頭\",\n\t\t\"locations\": [\"convenience_24h\"],\n\t\t\"floorId\": \"yuedu_ai_3\",\n\t\t\"once\": true\n\t});\n}"
        },
        {
            "type": "function",
            "function": "function () {\n\tcore.plugin.returnToAkiba();\n}"
        }
    ],
    "parallelDo": "",
    "events": {},
    "changeFloor": {},
    "beforeBattle": {},
    "afterBattle": {},
    "afterGetItem": {},
    "afterOpenDoor": {},
    "autoEvent": {},
    "cannotMove": {},
    "cannotMoveIn": {},
    "bgmap": [],
    "fgmap": []
}
